version: "3.9"

services:
  redis:
    image: redis:7
    container_name: graphql-gateway-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: graphql-gateway-app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379